"use client";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ConfigProvider, theme } from "antd";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { StyleProvider } from "@ant-design/cssinjs";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const metadata: Metadata = {
  title: "WeTheWorld",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[white] ${poppins.className}`}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: { poppins },
              },
              components: {
                Input: {
                  colorBgBase: "#ffffff",
                },
              },
            }}
          >
            <StyleProvider hashPriority="high">{children}</StyleProvider>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
